// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: emo_gRPC.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_emo_5fgRPC_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_emo_5fgRPC_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_emo_5fgRPC_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_emo_5fgRPC_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_emo_5fgRPC_2eproto;
namespace emo_gRPC {
class EmoConfig;
class EmoConfigDefaultTypeInternal;
extern EmoConfigDefaultTypeInternal _EmoConfig_default_instance_;
class EmoImg;
class EmoImgDefaultTypeInternal;
extern EmoImgDefaultTypeInternal _EmoImg_default_instance_;
class LabelSize;
class LabelSizeDefaultTypeInternal;
extern LabelSizeDefaultTypeInternal _LabelSize_default_instance_;
class NullMsg;
class NullMsgDefaultTypeInternal;
extern NullMsgDefaultTypeInternal _NullMsg_default_instance_;
class ResultList;
class ResultListDefaultTypeInternal;
extern ResultListDefaultTypeInternal _ResultList_default_instance_;
class ResultList_Result;
class ResultList_ResultDefaultTypeInternal;
extern ResultList_ResultDefaultTypeInternal _ResultList_Result_default_instance_;
}  // namespace emo_gRPC
PROTOBUF_NAMESPACE_OPEN
template<> ::emo_gRPC::EmoConfig* Arena::CreateMaybeMessage<::emo_gRPC::EmoConfig>(Arena*);
template<> ::emo_gRPC::EmoImg* Arena::CreateMaybeMessage<::emo_gRPC::EmoImg>(Arena*);
template<> ::emo_gRPC::LabelSize* Arena::CreateMaybeMessage<::emo_gRPC::LabelSize>(Arena*);
template<> ::emo_gRPC::NullMsg* Arena::CreateMaybeMessage<::emo_gRPC::NullMsg>(Arena*);
template<> ::emo_gRPC::ResultList* Arena::CreateMaybeMessage<::emo_gRPC::ResultList>(Arena*);
template<> ::emo_gRPC::ResultList_Result* Arena::CreateMaybeMessage<::emo_gRPC::ResultList_Result>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace emo_gRPC {

// ===================================================================

class NullMsg :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:emo_gRPC.NullMsg) */ {
 public:
  NullMsg();
  virtual ~NullMsg();

  NullMsg(const NullMsg& from);
  NullMsg(NullMsg&& from) noexcept
    : NullMsg() {
    *this = ::std::move(from);
  }

  inline NullMsg& operator=(const NullMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline NullMsg& operator=(NullMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const NullMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NullMsg* internal_default_instance() {
    return reinterpret_cast<const NullMsg*>(
               &_NullMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(NullMsg* other);
  friend void swap(NullMsg& a, NullMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NullMsg* New() const final {
    return CreateMaybeMessage<NullMsg>(nullptr);
  }

  NullMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<NullMsg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const NullMsg& from);
  void MergeFrom(const NullMsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NullMsg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "emo_gRPC.NullMsg";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_emo_5fgRPC_2eproto);
    return ::descriptor_table_emo_5fgRPC_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:emo_gRPC.NullMsg)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_emo_5fgRPC_2eproto;
};
// -------------------------------------------------------------------

class EmoConfig :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:emo_gRPC.EmoConfig) */ {
 public:
  EmoConfig();
  virtual ~EmoConfig();

  EmoConfig(const EmoConfig& from);
  EmoConfig(EmoConfig&& from) noexcept
    : EmoConfig() {
    *this = ::std::move(from);
  }

  inline EmoConfig& operator=(const EmoConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline EmoConfig& operator=(EmoConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EmoConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EmoConfig* internal_default_instance() {
    return reinterpret_cast<const EmoConfig*>(
               &_EmoConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(EmoConfig* other);
  friend void swap(EmoConfig& a, EmoConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline EmoConfig* New() const final {
    return CreateMaybeMessage<EmoConfig>(nullptr);
  }

  EmoConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EmoConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EmoConfig& from);
  void MergeFrom(const EmoConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EmoConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "emo_gRPC.EmoConfig";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_emo_5fgRPC_2eproto);
    return ::descriptor_table_emo_5fgRPC_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:emo_gRPC.EmoConfig)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_emo_5fgRPC_2eproto;
};
// -------------------------------------------------------------------

class ResultList_Result :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:emo_gRPC.ResultList.Result) */ {
 public:
  ResultList_Result();
  virtual ~ResultList_Result();

  ResultList_Result(const ResultList_Result& from);
  ResultList_Result(ResultList_Result&& from) noexcept
    : ResultList_Result() {
    *this = ::std::move(from);
  }

  inline ResultList_Result& operator=(const ResultList_Result& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResultList_Result& operator=(ResultList_Result&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ResultList_Result& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResultList_Result* internal_default_instance() {
    return reinterpret_cast<const ResultList_Result*>(
               &_ResultList_Result_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(ResultList_Result* other);
  friend void swap(ResultList_Result& a, ResultList_Result& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResultList_Result* New() const final {
    return CreateMaybeMessage<ResultList_Result>(nullptr);
  }

  ResultList_Result* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ResultList_Result>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ResultList_Result& from);
  void MergeFrom(const ResultList_Result& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResultList_Result* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "emo_gRPC.ResultList.Result";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_emo_5fgRPC_2eproto);
    return ::descriptor_table_emo_5fgRPC_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string label = 5;
  void clear_label();
  static const int kLabelFieldNumber = 5;
  const std::string& label() const;
  void set_label(const std::string& value);
  void set_label(std::string&& value);
  void set_label(const char* value);
  void set_label(const char* value, size_t size);
  std::string* mutable_label();
  std::string* release_label();
  void set_allocated_label(std::string* label);

  // float x0 = 1;
  void clear_x0();
  static const int kX0FieldNumber = 1;
  float x0() const;
  void set_x0(float value);

  // float y0 = 2;
  void clear_y0();
  static const int kY0FieldNumber = 2;
  float y0() const;
  void set_y0(float value);

  // float x1 = 3;
  void clear_x1();
  static const int kX1FieldNumber = 3;
  float x1() const;
  void set_x1(float value);

  // float y1 = 4;
  void clear_y1();
  static const int kY1FieldNumber = 4;
  float y1() const;
  void set_y1(float value);

  // @@protoc_insertion_point(class_scope:emo_gRPC.ResultList.Result)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr label_;
  float x0_;
  float y0_;
  float x1_;
  float y1_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_emo_5fgRPC_2eproto;
};
// -------------------------------------------------------------------

class ResultList :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:emo_gRPC.ResultList) */ {
 public:
  ResultList();
  virtual ~ResultList();

  ResultList(const ResultList& from);
  ResultList(ResultList&& from) noexcept
    : ResultList() {
    *this = ::std::move(from);
  }

  inline ResultList& operator=(const ResultList& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResultList& operator=(ResultList&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ResultList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResultList* internal_default_instance() {
    return reinterpret_cast<const ResultList*>(
               &_ResultList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(ResultList* other);
  friend void swap(ResultList& a, ResultList& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResultList* New() const final {
    return CreateMaybeMessage<ResultList>(nullptr);
  }

  ResultList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ResultList>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ResultList& from);
  void MergeFrom(const ResultList& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResultList* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "emo_gRPC.ResultList";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_emo_5fgRPC_2eproto);
    return ::descriptor_table_emo_5fgRPC_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef ResultList_Result Result;

  // accessors -------------------------------------------------------

  // repeated .emo_gRPC.ResultList.Result re_result = 1;
  int re_result_size() const;
  void clear_re_result();
  static const int kReResultFieldNumber = 1;
  ::emo_gRPC::ResultList_Result* mutable_re_result(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::emo_gRPC::ResultList_Result >*
      mutable_re_result();
  const ::emo_gRPC::ResultList_Result& re_result(int index) const;
  ::emo_gRPC::ResultList_Result* add_re_result();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::emo_gRPC::ResultList_Result >&
      re_result() const;

  // @@protoc_insertion_point(class_scope:emo_gRPC.ResultList)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::emo_gRPC::ResultList_Result > re_result_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_emo_5fgRPC_2eproto;
};
// -------------------------------------------------------------------

class LabelSize :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:emo_gRPC.LabelSize) */ {
 public:
  LabelSize();
  virtual ~LabelSize();

  LabelSize(const LabelSize& from);
  LabelSize(LabelSize&& from) noexcept
    : LabelSize() {
    *this = ::std::move(from);
  }

  inline LabelSize& operator=(const LabelSize& from) {
    CopyFrom(from);
    return *this;
  }
  inline LabelSize& operator=(LabelSize&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LabelSize& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LabelSize* internal_default_instance() {
    return reinterpret_cast<const LabelSize*>(
               &_LabelSize_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(LabelSize* other);
  friend void swap(LabelSize& a, LabelSize& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LabelSize* New() const final {
    return CreateMaybeMessage<LabelSize>(nullptr);
  }

  LabelSize* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LabelSize>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LabelSize& from);
  void MergeFrom(const LabelSize& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LabelSize* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "emo_gRPC.LabelSize";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_emo_5fgRPC_2eproto);
    return ::descriptor_table_emo_5fgRPC_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 w = 1;
  void clear_w();
  static const int kWFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::int32 w() const;
  void set_w(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 h = 2;
  void clear_h();
  static const int kHFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::int32 h() const;
  void set_h(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:emo_gRPC.LabelSize)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 w_;
  ::PROTOBUF_NAMESPACE_ID::int32 h_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_emo_5fgRPC_2eproto;
};
// -------------------------------------------------------------------

class EmoImg :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:emo_gRPC.EmoImg) */ {
 public:
  EmoImg();
  virtual ~EmoImg();

  EmoImg(const EmoImg& from);
  EmoImg(EmoImg&& from) noexcept
    : EmoImg() {
    *this = ::std::move(from);
  }

  inline EmoImg& operator=(const EmoImg& from) {
    CopyFrom(from);
    return *this;
  }
  inline EmoImg& operator=(EmoImg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EmoImg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EmoImg* internal_default_instance() {
    return reinterpret_cast<const EmoImg*>(
               &_EmoImg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(EmoImg* other);
  friend void swap(EmoImg& a, EmoImg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline EmoImg* New() const final {
    return CreateMaybeMessage<EmoImg>(nullptr);
  }

  EmoImg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EmoImg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EmoImg& from);
  void MergeFrom(const EmoImg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EmoImg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "emo_gRPC.EmoImg";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_emo_5fgRPC_2eproto);
    return ::descriptor_table_emo_5fgRPC_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes imgBuffer = 3;
  void clear_imgbuffer();
  static const int kImgBufferFieldNumber = 3;
  const std::string& imgbuffer() const;
  void set_imgbuffer(const std::string& value);
  void set_imgbuffer(std::string&& value);
  void set_imgbuffer(const char* value);
  void set_imgbuffer(const void* value, size_t size);
  std::string* mutable_imgbuffer();
  std::string* release_imgbuffer();
  void set_allocated_imgbuffer(std::string* imgbuffer);

  // int32 w = 1;
  void clear_w();
  static const int kWFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::int32 w() const;
  void set_w(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 h = 2;
  void clear_h();
  static const int kHFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::int32 h() const;
  void set_h(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:emo_gRPC.EmoImg)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr imgbuffer_;
  ::PROTOBUF_NAMESPACE_ID::int32 w_;
  ::PROTOBUF_NAMESPACE_ID::int32 h_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_emo_5fgRPC_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NullMsg

// -------------------------------------------------------------------

// EmoConfig

// -------------------------------------------------------------------

// ResultList_Result

// float x0 = 1;
inline void ResultList_Result::clear_x0() {
  x0_ = 0;
}
inline float ResultList_Result::x0() const {
  // @@protoc_insertion_point(field_get:emo_gRPC.ResultList.Result.x0)
  return x0_;
}
inline void ResultList_Result::set_x0(float value) {
  
  x0_ = value;
  // @@protoc_insertion_point(field_set:emo_gRPC.ResultList.Result.x0)
}

// float y0 = 2;
inline void ResultList_Result::clear_y0() {
  y0_ = 0;
}
inline float ResultList_Result::y0() const {
  // @@protoc_insertion_point(field_get:emo_gRPC.ResultList.Result.y0)
  return y0_;
}
inline void ResultList_Result::set_y0(float value) {
  
  y0_ = value;
  // @@protoc_insertion_point(field_set:emo_gRPC.ResultList.Result.y0)
}

// float x1 = 3;
inline void ResultList_Result::clear_x1() {
  x1_ = 0;
}
inline float ResultList_Result::x1() const {
  // @@protoc_insertion_point(field_get:emo_gRPC.ResultList.Result.x1)
  return x1_;
}
inline void ResultList_Result::set_x1(float value) {
  
  x1_ = value;
  // @@protoc_insertion_point(field_set:emo_gRPC.ResultList.Result.x1)
}

// float y1 = 4;
inline void ResultList_Result::clear_y1() {
  y1_ = 0;
}
inline float ResultList_Result::y1() const {
  // @@protoc_insertion_point(field_get:emo_gRPC.ResultList.Result.y1)
  return y1_;
}
inline void ResultList_Result::set_y1(float value) {
  
  y1_ = value;
  // @@protoc_insertion_point(field_set:emo_gRPC.ResultList.Result.y1)
}

// string label = 5;
inline void ResultList_Result::clear_label() {
  label_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ResultList_Result::label() const {
  // @@protoc_insertion_point(field_get:emo_gRPC.ResultList.Result.label)
  return label_.GetNoArena();
}
inline void ResultList_Result::set_label(const std::string& value) {
  
  label_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:emo_gRPC.ResultList.Result.label)
}
inline void ResultList_Result::set_label(std::string&& value) {
  
  label_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:emo_gRPC.ResultList.Result.label)
}
inline void ResultList_Result::set_label(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  label_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:emo_gRPC.ResultList.Result.label)
}
inline void ResultList_Result::set_label(const char* value, size_t size) {
  
  label_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:emo_gRPC.ResultList.Result.label)
}
inline std::string* ResultList_Result::mutable_label() {
  
  // @@protoc_insertion_point(field_mutable:emo_gRPC.ResultList.Result.label)
  return label_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ResultList_Result::release_label() {
  // @@protoc_insertion_point(field_release:emo_gRPC.ResultList.Result.label)
  
  return label_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ResultList_Result::set_allocated_label(std::string* label) {
  if (label != nullptr) {
    
  } else {
    
  }
  label_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), label);
  // @@protoc_insertion_point(field_set_allocated:emo_gRPC.ResultList.Result.label)
}

// -------------------------------------------------------------------

// ResultList

// repeated .emo_gRPC.ResultList.Result re_result = 1;
inline int ResultList::re_result_size() const {
  return re_result_.size();
}
inline void ResultList::clear_re_result() {
  re_result_.Clear();
}
inline ::emo_gRPC::ResultList_Result* ResultList::mutable_re_result(int index) {
  // @@protoc_insertion_point(field_mutable:emo_gRPC.ResultList.re_result)
  return re_result_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::emo_gRPC::ResultList_Result >*
ResultList::mutable_re_result() {
  // @@protoc_insertion_point(field_mutable_list:emo_gRPC.ResultList.re_result)
  return &re_result_;
}
inline const ::emo_gRPC::ResultList_Result& ResultList::re_result(int index) const {
  // @@protoc_insertion_point(field_get:emo_gRPC.ResultList.re_result)
  return re_result_.Get(index);
}
inline ::emo_gRPC::ResultList_Result* ResultList::add_re_result() {
  // @@protoc_insertion_point(field_add:emo_gRPC.ResultList.re_result)
  return re_result_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::emo_gRPC::ResultList_Result >&
ResultList::re_result() const {
  // @@protoc_insertion_point(field_list:emo_gRPC.ResultList.re_result)
  return re_result_;
}

// -------------------------------------------------------------------

// LabelSize

// int32 w = 1;
inline void LabelSize::clear_w() {
  w_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LabelSize::w() const {
  // @@protoc_insertion_point(field_get:emo_gRPC.LabelSize.w)
  return w_;
}
inline void LabelSize::set_w(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  w_ = value;
  // @@protoc_insertion_point(field_set:emo_gRPC.LabelSize.w)
}

// int32 h = 2;
inline void LabelSize::clear_h() {
  h_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LabelSize::h() const {
  // @@protoc_insertion_point(field_get:emo_gRPC.LabelSize.h)
  return h_;
}
inline void LabelSize::set_h(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  h_ = value;
  // @@protoc_insertion_point(field_set:emo_gRPC.LabelSize.h)
}

// -------------------------------------------------------------------

// EmoImg

// int32 w = 1;
inline void EmoImg::clear_w() {
  w_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 EmoImg::w() const {
  // @@protoc_insertion_point(field_get:emo_gRPC.EmoImg.w)
  return w_;
}
inline void EmoImg::set_w(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  w_ = value;
  // @@protoc_insertion_point(field_set:emo_gRPC.EmoImg.w)
}

// int32 h = 2;
inline void EmoImg::clear_h() {
  h_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 EmoImg::h() const {
  // @@protoc_insertion_point(field_get:emo_gRPC.EmoImg.h)
  return h_;
}
inline void EmoImg::set_h(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  h_ = value;
  // @@protoc_insertion_point(field_set:emo_gRPC.EmoImg.h)
}

// bytes imgBuffer = 3;
inline void EmoImg::clear_imgbuffer() {
  imgbuffer_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& EmoImg::imgbuffer() const {
  // @@protoc_insertion_point(field_get:emo_gRPC.EmoImg.imgBuffer)
  return imgbuffer_.GetNoArena();
}
inline void EmoImg::set_imgbuffer(const std::string& value) {
  
  imgbuffer_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:emo_gRPC.EmoImg.imgBuffer)
}
inline void EmoImg::set_imgbuffer(std::string&& value) {
  
  imgbuffer_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:emo_gRPC.EmoImg.imgBuffer)
}
inline void EmoImg::set_imgbuffer(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  imgbuffer_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:emo_gRPC.EmoImg.imgBuffer)
}
inline void EmoImg::set_imgbuffer(const void* value, size_t size) {
  
  imgbuffer_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:emo_gRPC.EmoImg.imgBuffer)
}
inline std::string* EmoImg::mutable_imgbuffer() {
  
  // @@protoc_insertion_point(field_mutable:emo_gRPC.EmoImg.imgBuffer)
  return imgbuffer_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* EmoImg::release_imgbuffer() {
  // @@protoc_insertion_point(field_release:emo_gRPC.EmoImg.imgBuffer)
  
  return imgbuffer_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void EmoImg::set_allocated_imgbuffer(std::string* imgbuffer) {
  if (imgbuffer != nullptr) {
    
  } else {
    
  }
  imgbuffer_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), imgbuffer);
  // @@protoc_insertion_point(field_set_allocated:emo_gRPC.EmoImg.imgBuffer)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace emo_gRPC

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_emo_5fgRPC_2eproto
